### ISSUE TITLE
Recaptcha validation - need to be done in ajax ?

### ISSUE THREAD

**Issue by lenybernard** [Victoire/WidgetFormBundle#34]
I've just installed and test your recaptcha integration, it does not work fully. If you're not a bot and you don't click on the "I'm not a robot", you are totally screwed because you lost your form content. That could happend, you simply ddidn't payed attention or just because you pressed **enter** while having some focus in form.

So I think the validation should be done in ajax. I guess the _normal_ form submit should also be done in ajax, what do you think ?

Can you please manage this issue @Matteo-Peronnet ?
Thank you

**Comment by Matteo-Peronnet** [comment]
Yes, when you fill the form and if you don't check "I'm not a robot", you lost your form content, this is because we can't have HTM5 form validation with this input.
So, i think this is possible to solve this with ajax as you said. About normal form, this can be useful when we have an error in the controller with the regex validation, currently this resets the form. Moreover with this approach we will have the same code/validation for any form.

Yes, i'm going to solve this issue.

**Comment by Matteo-Peronnet** [comment]
I just saw with @paulandrieux, it's difficult to make the validation in ajax. The method who handle the form in the FormController doest not use `form->handlerequest()`, so the data aren't hydrated. We can't re-render the form with his data. 

The data on the form are processed procedurally, at no time we persist this data. 

I think we can return an array of the data who was post and then process them in javascript, but I don't think that's the right solution. Because there is a feature who allow the form to make a redirection if the form is succeed. That would involve a redirection from javascript ?

Another solution, is to use a callback provide by reCAPTCHA to check if the reCAPTCHA is checked. With this method this will not change much the current validation of the form. I'll see about that solution and see what's possible.
